### PR TITLE
backup: add example for backup restore migrate

### PR DESCRIPTION
**Pull request by Xieql**
**What type of PR is this?**

**What this PR does / why we need it**:

add backup, restore and migrate YAML examples to provide guidelines for more use cases and configuration options

part of https://github.com/kurator-dev/kurator/pull/374

**Which issue(s) this PR fixes**:
Fixes #

**Special notes for your reviewer**:

**Does this PR introduce a user-facing change?**:

```release-note
backup: add example for backup restore migrate
```

### CODE REVIEW

**Comment by Xieql** [comment]
@hzxuzhonghu PTAL

**Comment by Xieql** [comment]
> should there be some docs along with these examples

yes, those example will be referred by the subsequent doc PR

**Comment by hzxuzhonghu** [comment]
So those docs should be alone with, otherwise i do not know why we need these yamls

**Comment by Xieql** [comment]
> So those docs should be alone with, otherwise i do not know why we need these yamls

ok，I will close this pr

**Pull request closed without merging**
