### PR TITLE
Rename to NewKuratorCommand

### PR DESCRIPTION
**Pull request by hzxuzhonghu**
**Does this PR introduce a user-facing change?**:

```release-note
NONE
```

### CODE REVIEW

**Comment by zirain** [comment]
range map randomness, in real config is ok, but will cause UT failed.

**Comment by gy95** [comment]
> range map randomness, in real config is ok, but will cause UT fail.

How to fix this unit test? can just compare the two string lengths?

**Comment by zirain** [comment]
> > range map randomness, in real config is ok, but will cause UT fail.
> 
> How to fix this unit test? can just compare the two string lengths?

I will change the implement

**Comment by zirain** [comment]
UT fail fixed by https://github.com/kurator-dev/kurator/pull/9

**Pull request merged**
