### PR TITLE
Added fleet api

### PR DESCRIPTION
**Pull request by hzxuzhonghu**
**What type of PR is this?**

/kind api-change

Proposal: [here](https://docs.google.com/document/d/1bv3HQqMZhLPDnf2ZBFcO6KjUb1TxET_kRf5YJSaJSZ8/edit#)

**What this PR does / why we need it**:

**Which issue(s) this PR fixes**:
Fixes #

**Special notes for your reviewer**:

**Does this PR introduce a user-facing change?**:

```release-note
Added fleet api
```

### CODE REVIEW

**Comment by zirain** [comment]
two concerns:
1. need review on `Note: there is a limitation here, we donot support multi fleets in one namespace`
2. will fleet support default propagation policy?

**Comment by hzxuzhonghu** [comment]
>need review on Note: there is a limitation here, we donot support multi fleets in one namespace

I do not think in real case, there is a need to deploy multi fleet in one namespace. This is the management cluster, user should not care about namespace at all. 

>will fleet support default propagation policy?

This is listed in the excel

**Pull request merged**
