### PR TITLE
Fix: typo of file and func name

### PR DESCRIPTION
**Pull request by Flying-Tom**
**What type of PR is this?**

/kind bug

**What this PR does / why we need it**:

Some typo found:
-  `pkg/plugin/prometheus/pulgin.go`
-  Render method name of some plugins of fleet-manager

**Which issue(s) this PR fixes**:
Fixes #

**Special notes for your reviewer**:

**Does this PR introduce a user-facing change?**:

```release-note
NONE
```

### CODE REVIEW

**Review by zirain — APPROVED** [review]
/lgtm

**Review by hzxuzhonghu — APPROVED** [review]
Thank you

**Comment by hzxuzhonghu** [comment]
Please fix DCO, 
In your local branch, run: git rebase HEAD~2 --signoff
Force push your changes to overwrite the branch: git push --force-with-lease origin typo-fix

**Pull request merged**
