### PR TITLE
doc: add proposal template

### PR DESCRIPTION
**Pull request by Xieql**
**What type of PR is this?**

/kind documentation

**What this PR does / why we need it**:

add proposal template

from https://github.com/karmada-io/karmada/tree/master/docs/proposals/proposal-template
**Which issue(s) this PR fixes**:
Fixes #

**Special notes for your reviewer**:

**Does this PR introduce a user-facing change?**:

```release-note
add proposal template
```

### CODE REVIEW

**Comment by Xieql** [comment]
ptal @hzxuzhonghu

**Review by hzxuzhonghu — APPROVED** [review]
/lgtm

**Pull request merged**
